#!/usr/bin/env node
/*
 * A dev/debugging script to run a command against Amon's redis.
 */

var p = console.log;
var exec = require('child_process').exec;
var redis = require('redis');

function getConfig(callback) {
  var config = {
    redis: {
      port: 6379
    }
  };
  exec('sdc-mapi /machines?tag.smartdc_role=redis | json -H 0.ips.0.address',
    function (err, stdout, stderr) {
      if (err) return callback(err);
      config.redis.host = stdout.trim();
      callback(null, config);
  });
}


getConfig(function (err, config) {
  var client = redis.createClient(config.redis.port, config.redis.host);
  client.select(1);  // Amon's database.
  var cmd = process.argv[2];
  var args = process.argv.slice(3);
  if (cmd.length) {
      client.send_command(cmd, args, function (err, reply) {
          //redis.print(err, reply);
          if (err) {
              console.log("Error:", err);
          }
          if (reply) {
              console.log(JSON.stringify(reply, null, 2));
          }
      });
  }
  client.quit();
})
