#!/bin/bash
#
# Rsync the *test suite* files in this working copy to the install on the QA
# "nightly" staging setup (i.e. the small DC setup from last night's build of
# SDC master).
#

#set -x
TOP=$(cd $(dirname $0)/../; pwd)
RELAY_DIR=$TOP/relay
NODE=root@10.99.99.7

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts='--exclude "*.node"'
fi

rsync -av ${TOP}/test/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/test/ \
    $extraOpts \
    --exclude "*.log" \
    --exclude "config.json" \
    --exclude "prep.json" \
    --exclude tmp/

if [[ $(uname -s) != "SunOS" ]]; then
    # Restore buffertools.node that is always blown away the first time the
    # above is done.
    # TODO: same for dtrace_provider.node.
    ssh $NODE cp /opt/smartdc/agents/lib/node_modules/amon-relay/test/node_modules/ldapjs/node_modules/buffertools/build/Release/buffertools.node \
        /opt/smartdc/agents/lib/node_modules/amon-relay/test/node_modules/sdc-clients/node_modules/ldapjs/node_modules/buffertools/build/Release/buffertools.node
fi

rsync -av ${TOP}/plugins/test/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/node_modules/amon-plugins/test/
