#!/bin/bash
#
# Rsync the master in this working copy to the install on the bh1-kvm7 headnode
# GZ.
#

#set -x
TOP=$(cd $(dirname $0)/../; pwd)
NODE=root@10.2.207.2
JSON3=$TOP/test/node_modules/.bin/json3

if [[ -z "$AMON_ZONE" ]]; then
    AMON_ZONE=$(ssh $NODE "/opt/smartdc/bin/sdc-zapi /vms" 2>/dev/null \
        | $JSON3 -H -c 'this.tags && this.tags.smartdc_role === "amon"' \
            -c 'this.state === "running"' 0.uuid)
fi
echo "AMON_ZONE: $AMON_ZONE"

rsync -av ${TOP}/master/ \
    $NODE:/zones/$AMON_ZONE/root/opt/smartdc/amon/ \
    --exclude "*.node" \
    --exclude amon-common \
    --exclude amon-plugins \
    --exclude tmp/
rsync -av ${TOP}/common/ \
    $NODE:/zones/$AMON_ZONE/root/opt/smartdc/amon/node_modules/amon-common/ \
    --exclude "*.node" \
    --exclude tmp/
rsync -av ${TOP}/plugins/ \
    $NODE:/zones/$AMON_ZONE/root/opt/smartdc/amon/node_modules/amon-plugins/ \
    --exclude "*.node" \
    --exclude tmp/

ssh ${NODE} svcadm -z ${AMON_ZONE} clear amon-master
ssh ${NODE} svcadm -z ${AMON_ZONE} restart amon-master
