#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Rsync the agent in this working copy to the install on the COAL headnode GZ.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
AGENT_DIR=$TOP/agent
COAL=root@10.99.99.7

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node"
fi

rsync -av ${AGENT_DIR}/ \
    $COAL:/opt/smartdc/agents/lib/node_modules/amon-agent/ \
    --exclude deps/ \
    $extraOpts \
    --exclude amon-common \
    --exclude amon-plugins \
    --exclude tmp/
rsync -av ${TOP}/common/ \
    $COAL:/opt/smartdc/agents/lib/node_modules/amon-agent/node_modules/amon-common/ \
    $extraOpts \
    --exclude tmp/
rsync -av ${TOP}/plugins/ \
    $COAL:/opt/smartdc/agents/lib/node_modules/amon-agent/node_modules/amon-plugins/ \
    $extraOpts \
    --exclude tmp/

ssh ${COAL} svcadm clear amon-agent || true
ssh ${COAL} svcadm restart amon-agent
