#!/bin/bash
#
# Rsync the relay in this working copy to the install on the bh1-kvm7 GZ.
#

#set -x
TOP=$(cd $(dirname $0)/../; pwd)
RELAY_DIR=$TOP/relay
NODE=root@10.2.207.2

rsync -av ${RELAY_DIR}/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/ \
    --exclude deps/ \
    --exclude "*.node" \
    --exclude amon-common \
    --exclude amon-plugins \
    --exclude zsock/ \
    --exclude zutil/ \
    --exclude tmp/
rsync -av ${TOP}/common/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/node_modules/amon-common/ \
    --exclude "*.node" \
    --exclude tmp/
rsync -av ${TOP}/plugins/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/node_modules/amon-plugins/ \
    --exclude "*.node" \
    --exclude tmp/
rsync -av ${TOP}/test/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/test/ \
    --exclude "*.node" \
    --exclude "*.log" \
    --exclude "config.json" \
    --exclude "prep.json" \
    --exclude tmp/

ssh ${NODE} svcadm clear amon-relay
ssh ${NODE} svcadm restart amon-relay
