#!/bin/bash
#
# Rsync the *test suite* files in this working copy to the install on the QA
# "nightly" staging setup (i.e. the small DC setup from last night's build of
# SDC master).
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
RELAY_DIR=$TOP/relay
NODE=root@10.2.109.20

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node"
fi

rsync -av ${TOP}/test/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/test/ \
    $extraOpts \
    --exclude "*.log" \
    --exclude "config.json" \
    --exclude "prep.json" \
    --exclude tmp/

rsync -av ${TOP}/plugins/test/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/node_modules/amon-plugins/test/
