#!/bin/bash
#
# Rsync the agent in this working copy to the install on the bh1-kvm7
# headnode GZ.
#

#set -x
TOP=$(cd $(dirname $0)/../; pwd)
AGENT_DIR=$TOP/agent
NODE=root@10.2.207.2
SSH_OPTIONS="-q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
SSH="ssh $SSH_OPTIONS"

rsync -av -e "$SSH" ${AGENT_DIR}/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-agent/ \
    --exclude deps/ \
    --exclude "*.node" \
    --exclude amon-common \
    --exclude amon-plugins \
    --exclude tmp/
rsync -av -e "$SSH" ${TOP}/common/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-agent/node_modules/amon-common/ \
    --exclude "*.node" \
    --exclude tmp/
rsync -av -e "$SSH" ${TOP}/plugins/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-agent/node_modules/amon-plugins/ \
    --exclude "*.node" \
    --exclude tmp/

ssh ${NODE} svcadm clear amon-agent
ssh ${NODE} svcadm restart amon-agent
