#!/bin/bash
#
# Rsync the master in this working copy to the install on the COAL headnode GZ.
#

#set -x
TOP=$(cd $(dirname $0)/../; pwd)
NODE=root@10.99.99.7

if [[ -z "$AMON_ZONE" ]]; then
    AMON_ZONE=$(ssh $NODE "/opt/smartdc/bin/sdc-vmapi /vms" 2>/dev/null \
        | json -H -c 'this.tags && this.tags.smartdc_role === "amon"' \
            -c 'this.state === "running"' 0.uuid)
fi
echo "AMON_ZONE: $AMON_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts='--exclude "*.node"'
fi

rsync -av ${TOP}/master/ \
    $NODE:/zones/$AMON_ZONE/root/opt/smartdc/amon/ \
    $extraOpts \
    --exclude amon-common \
    --exclude amon-plugins \
    --exclude tmp/
if [[ $(uname -s) != "SunOS" ]]; then
    # Restore buffertools.node that is always blown away the first time the
    # above is done.
    # TODO: same for dtrace_provider.node.
    ssh $NODE cp /zones/$AMON_ZONE/root/opt/smartdc/amon/node_modules/ldapjs/node_modules/buffertools/build/Release/buffertools.node \
        /zones/$AMON_ZONE/root/opt/smartdc/amon/node_modules/sdc-clients/node_modules/ldapjs/node_modules/buffertools/build/Release/buffertools.node
fi
rsync -av ${TOP}/common/ \
    $NODE:/zones/$AMON_ZONE/root/opt/smartdc/amon/node_modules/amon-common/ \
    --exclude "*.node" \
    --exclude tmp/
rsync -av ${TOP}/plugins/ \
    $NODE:/zones/$AMON_ZONE/root/opt/smartdc/amon/node_modules/amon-plugins/ \
    --exclude "*.node" \
    --exclude tmp/

ssh ${NODE} svcadm -z ${AMON_ZONE} clear amon-master
ssh ${NODE} svcadm -z ${AMON_ZONE} restart amon-master
