#!/bin/bash
#
# Rsync the relay in this working copy to the install on the QA
# "nightly" staging setup (i.e. the small DC setup from last
# night's build of SDC master).
#

#set -x
TOP=$(cd $(dirname $0)/../; pwd)
NODE=root@10.2.106.7
SSH_OPTIONS="-q -i $HOME/.ssh/automation.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
SSH="ssh $SSH_OPTIONS"

rsync -av -e "$SSH" ${RELAY_DIR}/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/ \
    --exclude deps/ \
    --exclude "*.node" \
    --exclude amon-common \
    --exclude amon-plugins \
    --exclude buffertools \
    --exclude zsock/ \
    --exclude zutil/ \
    --exclude tmp/
rsync -av -e "$SSH" ${TOP}/common/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/node_modules/amon-common/ \
    --exclude "*.node" \
    --exclude tmp/
rsync -av -e "$SSH" ${TOP}/plugins/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/node_modules/amon-plugins/ \
    --exclude "*.node" \
    --exclude tmp/
rsync -av -e "$SSH" ${TOP}/test/ \
    $NODE:/opt/smartdc/agents/lib/node_modules/amon-relay/test/ \
    --exclude "*.node" \
    --exclude "*.log" \
    --exclude "config.json" \
    --exclude "prep.json" \
    --exclude tmp/

ssh ${NODE} svcadm clear amon-relay
ssh ${NODE} svcadm restart amon-relay
